import React from 'react';
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles } from 'lucide-react';

export default function InsightNarratives() {
  // In a real app, this would be generated by an LLM via the backend
  // Here we use template-based generation based on common patterns
  
  const insights = [
    {
      title: "Warehouse Safety Trend",
      text: "Safety performance in the Warehouse has been declining. We've detected 3 near-misses in the past 2 weeks, and our models predict 2-3 serious incidents in the next 30 days if current trends continue. We recommend increasing safety training and implementing additional hazard controls."
    },
    {
      title: "Risk Reduction Opportunity",
      text: "The Chemical Storage area shows high risk (87/100). Equipment maintenance is overdue, and hazard assessments indicate inadequate ventilation. Implementing the recommended ventilation upgrade could reduce risk by 34%."
    },
    {
      title: "Positive Progress",
      text: "Good news: Production area risk has improved from 65 to 42 in the past month. This is due to the new lockout/tagout procedures implemented 3 weeks ago. Continue monitoring and maintain current practices."
    }
  ];

  return (
    <div className="space-y-4">
      <h3 className="text-lg font-bold text-white flex items-center gap-2">
        <Sparkles className="h-5 w-5 text-yellow-400" />
        AI Narrative Insights
      </h3>
      
      <div className="grid gap-4">
        {insights.map((insight, index) => (
          <div key={index} className="bg-gradient-to-r from-[#1a1a2e] to-[#1f1f35] border border-[#3a3a5a] rounded-xl p-4 shadow-sm relative overflow-hidden group">
            <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-[#8b5cf6] to-transparent opacity-50 group-hover:opacity-100 transition-opacity"></div>
            <h4 className="text-[#8b5cf6] font-semibold mb-2 text-sm uppercase tracking-wide">{insight.title}</h4>
            <p className="text-white/90 leading-relaxed text-sm">
              {insight.text}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}